name: CI

on:
  push:
    branches:
      - "**"
  pull_request:
    branches:
      - main
  schedule:
    - cron: "0 0 * * MON"
  workflow_dispatch:

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Test 1. A target branch that has never been synced before
        uses: ./
        with:
          upstream-repository: fem-on-colab/is-synced-with-upstream-action
          upstream-ref: test-1-source
          target-ref: test-1-target
          file-patterns: tests/*.py **/*.txt
          commit-message-prefix: Sync with source branch
          push-changes: false
          expect-out-of-sync: true
          expected-target-ref: test-1-expected-diff
      - name: Test 2. Changes to an existing file
        uses: ./
        with:
          upstream-repository: fem-on-colab/is-synced-with-upstream-action
          upstream-ref: test-2-source
          target-ref: test-2-target
          file-patterns: tests/*.py **/*.txt
          commit-message-prefix: Sync with source branch
          push-changes: false
          expect-out-of-sync: true
          expected-target-ref: test-2-expected-diff
      - name: Test 3. A new file is added
        uses: ./
        with:
          upstream-repository: fem-on-colab/is-synced-with-upstream-action
          upstream-ref: test-3-source
          target-ref: test-3-target
          file-patterns: tests/*.py **/*.txt
          commit-message-prefix: Sync with source branch
          push-changes: false
          expect-out-of-sync: true
          expected-target-ref: test-3-expected-diff
      - name: Warn if scheduled workflow is about to be disabled
        if: github.repository == 'fem-on-colab/is-synced-with-upstream-action' && github.ref == 'refs/heads/main' && github.event_name == 'schedule'
        uses: fem-on-colab/warn-workflow-about-to-be-disabled-action@main
        with:
          workflow-filename: ci.yml
          days-elapsed: 50
